import type { Tool } from "@modelcontextprotocol/sdk/types.js";

import { filterTools } from "./core.ts";
import type { FilterToolsOptions, ToolDescriptor } from "./core.ts";

const REVIEWED_TOOL_NAMES = [
  "easyeda_api_call",
  "easyeda_api_inventory",
  "easyeda_board_dimensions",
  "easyeda_board_features",
  "easyeda_board_layers",
  "easyeda_board_stackup",
  "easyeda_bom_export",
  "easyeda_bom_generate",
  "easyeda_bom_quality_report",
  "easyeda_bom_sourcing",
  "easyeda_bom_validate",
  "easyeda_bridge_probe_methods",
  "easyeda_bridge_status",
  "easyeda_canvas_capture",
  "easyeda_canvas_capture_region",
  "easyeda_canvas_locate",
  "easyeda_catalog_list",
  "easyeda_catalog_verify_device",
  "easyeda_component_probe",
  "easyeda_design_rules_lookup",
  "easyeda_drc_run",
  "easyeda_erc_run",
  "easyeda_execute",
  "easyeda_export_gerbers",
  "easyeda_export_netlist",
  "easyeda_export_pdf",
  "easyeda_export_pick_place",
  "easyeda_get_capabilities",
  "easyeda_get_feature_flags",
  "easyeda_get_server_config",
  "easyeda_get_tool_profiles",
  "easyeda_health_check",
  "easyeda_jlcpcb_quote_workflow",
  "easyeda_live_smoke_report",
  "easyeda_live_write_regression",
  "easyeda_observability_report",
  "easyeda_pcb_add_silkscreen_line",
  "easyeda_pcb_add_text",
  "easyeda_pcb_add_track",
  "easyeda_pcb_add_via",
  "easyeda_pcb_add_zone",
  "easyeda_pcb_autoroute",
  "easyeda_pcb_components",
  "easyeda_pcb_constraint_check",
  "easyeda_pcb_constraint_report",
  "easyeda_pcb_delete_component",
  "easyeda_pcb_export_route_context",
  "easyeda_pcb_floorplan",
  "easyeda_pcb_modify_component",
  "easyeda_pcb_place_component",
  "easyeda_pcb_place_component_group",
  "easyeda_pcb_production_review",
  "easyeda_pcb_route_path_plan",
  "easyeda_pcb_tracks",
  "easyeda_pcb_vias",
  "easyeda_post_write_qa",
  "easyeda_power_tree_analyze",
  "easyeda_production_qa_artifacts",
  "easyeda_project_begin_transaction",
  "easyeda_project_commit_transaction",
  "easyeda_project_get_transaction_status",
  "easyeda_project_rollback_transaction",
  "easyeda_project_save",
  "easyeda_project_validate_transaction",
  "easyeda_rule_check_summary",
  "easyeda_run_self_test",
  "easyeda_schematic_add_circle",
  "easyeda_schematic_add_polygon",
  "easyeda_schematic_add_rectangle",
  "easyeda_schematic_add_text",
  "easyeda_schematic_add_wire",
  "easyeda_schematic_audit_imported_design",
  "easyeda_schematic_batch_write",
  "easyeda_schematic_capture_full_page",
  "easyeda_schematic_check_collisions",
  "easyeda_schematic_check_placement",
  "easyeda_schematic_component_pins",
  "easyeda_schematic_components",
  "easyeda_schematic_connect_pin_to_net",
  "easyeda_schematic_connect_pins_by_net",
  "easyeda_schematic_connectivity_fingerprint",
  "easyeda_schematic_create_net_flag",
  "easyeda_schematic_create_net_port",
  "easyeda_schematic_delete_primitive",
  "easyeda_schematic_layout_autofix",
  "easyeda_schematic_layout_autofix_apply",
  "easyeda_schematic_layout_qa",
  "easyeda_schematic_modify_primitive",
  "easyeda_schematic_net_detail",
  "easyeda_schematic_nets",
  "easyeda_schematic_place_component",
  "easyeda_schematic_plan_layout",
  "easyeda_schematic_plan_safe_region",
  "easyeda_schematic_preview_imported_normalization",
  "easyeda_schematic_primitive_bounds",
  "easyeda_schematic_search_device",
  "easyeda_schematic_set_pin_no_connect",
  "easyeda_schematic_set_title_block",
  "easyeda_schematic_sheet_info",
  "easyeda_schematic_sync_to_pcb",
  "easyeda_schematic_validate_netlist",
  "easyeda_schematic_verify_write",
  "easyeda_schematic_wires",
  "easyeda_semantic_erc_auto",
  "easyeda_semantic_erc_validate",
  "easyeda_simulate_operating_point",
  "easyeda_simulate_transient",
  "easyeda_wire_probe",
  "easyeda_workflow_connector_breakout",
  "easyeda_workflow_decouple_ic",
  "easyeda_workflow_layout_section",
  "easyeda_workflow_led_blinker",
  "easyeda_workflow_ne555_astable",
  "easyeda_workflow_place_block",
  "easyeda_workflow_power_rail",
  "easyeda_workflow_rp2040_servo_module",
] as const;

const REVIEWED_READ_ONLY_TOOL_NAMES = new Set<string>([
  "easyeda_api_inventory",
  "easyeda_board_dimensions",
  "easyeda_board_features",
  "easyeda_board_layers",
  "easyeda_board_stackup",
  "easyeda_bom_generate",
  "easyeda_bom_quality_report",
  "easyeda_bom_sourcing",
  "easyeda_bom_validate",
  "easyeda_bridge_probe_methods",
  "easyeda_bridge_status",
  "easyeda_canvas_capture",
  "easyeda_canvas_capture_region",
  "easyeda_canvas_locate",
  "easyeda_catalog_list",
  "easyeda_component_probe",
  "easyeda_design_rules_lookup",
  "easyeda_get_capabilities",
  "easyeda_get_feature_flags",
  "easyeda_get_server_config",
  "easyeda_get_tool_profiles",
  "easyeda_health_check",
  "easyeda_jlcpcb_quote_workflow",
  "easyeda_live_smoke_report",
  "easyeda_observability_report",
  "easyeda_pcb_components",
  "easyeda_pcb_constraint_check",
  "easyeda_pcb_constraint_report",
  "easyeda_pcb_export_route_context",
  "easyeda_pcb_production_review",
  "easyeda_pcb_tracks",
  "easyeda_pcb_vias",
  "easyeda_power_tree_analyze",
  "easyeda_production_qa_artifacts",
  "easyeda_project_get_transaction_status",
  "easyeda_project_validate_transaction",
  "easyeda_rule_check_summary",
  "easyeda_schematic_audit_imported_design",
  "easyeda_schematic_capture_full_page",
  "easyeda_schematic_check_collisions",
  "easyeda_schematic_check_placement",
  "easyeda_schematic_component_pins",
  "easyeda_schematic_components",
  "easyeda_schematic_connectivity_fingerprint",
  "easyeda_schematic_layout_autofix",
  "easyeda_schematic_layout_qa",
  "easyeda_schematic_net_detail",
  "easyeda_schematic_nets",
  "easyeda_schematic_plan_layout",
  "easyeda_schematic_plan_safe_region",
  "easyeda_schematic_preview_imported_normalization",
  "easyeda_schematic_primitive_bounds",
  "easyeda_schematic_search_device",
  "easyeda_schematic_sheet_info",
  "easyeda_schematic_validate_netlist",
  "easyeda_schematic_verify_write",
  "easyeda_schematic_wires",
  "easyeda_semantic_erc_auto",
  "easyeda_semantic_erc_validate",
  "easyeda_simulate_operating_point",
  "easyeda_simulate_transient",
  "easyeda_wire_probe",
]);

export function reviewedUpstreamToolCatalog(): Tool[] {
  return REVIEWED_TOOL_NAMES.map((name) => {
    const readOnly = REVIEWED_READ_ONLY_TOOL_NAMES.has(name);
    return {
      name,
      title: name,
      description:
        "Reviewed static catalog entry. Live tool descriptions and schemas are unavailable while orphan-risk quarantine is active. This lookup does not start the upstream process or connect to EasyEDA.",
      annotations: {
        readOnlyHint: readOnly,
        destructiveHint: !readOnly,
        idempotentHint: false,
        openWorldHint: false,
      },
      inputSchema: {
        type: "object",
        description:
          "Static quarantine catalog only; query live discovery after recovery for the exact input schema.",
      },
    };
  });
}

export async function discoverReviewedOrLiveTools(
  assertLiveDispatchAllowed: () => Promise<unknown>,
  listLiveTools: () => Promise<readonly ToolDescriptor[]>,
  options: Readonly<FilterToolsOptions>,
): Promise<ReturnType<typeof filterTools>> {
  try {
    await assertLiveDispatchAllowed();
  } catch {
    return filterTools(reviewedUpstreamToolCatalog(), options);
  }
  return filterTools(await listLiveTools(), options);
}
